// Copyright 2001-2026 Crytek GmbH / Crytek Group. All rights reserved.
// CryEngine Pixel Formats & Direct3D DXGI Format Mapping

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u32)]
pub enum DxgiFormat {
    Unknown = 0,
    R32G32B32A32Float = 2,
    R32G32Float = 16,
    R32Float = 41,
    R16G16B16A16Float = 10,
    R16G16B16A16Unorm = 11,
    R16G16Float = 34,
    R16G16Unorm = 35,
    R16Float = 54,
    R16Unorm = 56,
    R8G8B8A8Unorm = 28,
    R8G8B8A8UnormSrgb = 29,
    B8G8R8A8Unorm = 87,
    B8G8R8A8UnormSrgb = 91,
    B8G8R8X8Unorm = 88,
    B8G8R8X8UnormSrgb = 93,
    R8G8Unorm = 49,
    R8Unorm = 61,
    A8Unorm = 65,
    BC1Unorm = 71,
    BC1UnormSrgb = 72,
    BC2Unorm = 74,
    BC2UnormSrgb = 75,
    BC3Unorm = 77,
    BC3UnormSrgb = 78,
    BC4Unorm = 80,
    BC4Snorm = 81,
    BC5Unorm = 83,
    BC5Snorm = 84,
    BC6HUf16 = 95,
    BC6HSf16 = 96,
    BC7Unorm = 98,
    BC7UnormSrgb = 99,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EPixelFormat {
    A8R8G8B8 = 0,
    X8R8G8B8,
    R8G8B8,
    BC1,
    BC1a,
    BC2,
    BC2t,
    BC3,
    BC3t,
    BC4,
    BC4s,
    BC5,
    BC5s,
    BC6UH,
    BC7,
    BC7t,
    CTX1,
}

#[derive(Debug, Clone)]
pub struct PixelFormatInfo {
    pub bytes_per_block: usize,
    pub channels: usize,
    pub has_alpha: bool,
    pub min_width: usize,
    pub min_height: usize,
    pub block_width: usize,
    pub block_height: usize,
    pub dxgi_format: DxgiFormat,
    pub name: &'static str,
    pub is_compressed: bool,
}

pub struct CPixelFormats;

impl CPixelFormats {
    pub fn get_pixel_format_info(format: EPixelFormat) -> &'static PixelFormatInfo {
        match format {
            EPixelFormat::A8R8G8B8 => &PixelFormatInfo {
                bytes_per_block: 4,
                channels: 4,
                has_alpha: true,
                min_width: 1,
                min_height: 1,
                block_width: 1,
                block_height: 1,
                dxgi_format: DxgiFormat::B8G8R8A8Unorm,
                name: "A8R8G8B8",
                is_compressed: false,
            },
            EPixelFormat::X8R8G8B8 => &PixelFormatInfo {
                bytes_per_block: 4,
                channels: 3,
                has_alpha: false,
                min_width: 1,
                min_height: 1,
                block_width: 1,
                block_height: 1,
                dxgi_format: DxgiFormat::B8G8R8X8Unorm,
                name: "X8R8G8B8",
                is_compressed: false,
            },
            EPixelFormat::R8G8B8 => &PixelFormatInfo {
                bytes_per_block: 4,
                channels: 3,
                has_alpha: false,
                min_width: 1,
                min_height: 1,
                block_width: 1,
                block_height: 1,
                dxgi_format: DxgiFormat::B8G8R8X8Unorm,
                name: "R8G8B8",
                is_compressed: false,
            },
            EPixelFormat::BC1 => &PixelFormatInfo {
                bytes_per_block: 8,
                channels: 3,
                has_alpha: false,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC1Unorm,
                name: "BC1",
                is_compressed: true,
            },
            EPixelFormat::BC1a => &PixelFormatInfo {
                bytes_per_block: 8,
                channels: 4,
                has_alpha: true,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC1Unorm,
                name: "BC1a",
                is_compressed: true,
            },
            EPixelFormat::BC2 | EPixelFormat::BC2t => &PixelFormatInfo {
                bytes_per_block: 16,
                channels: 4,
                has_alpha: true,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC2Unorm,
                name: "BC2",
                is_compressed: true,
            },
            EPixelFormat::BC3 | EPixelFormat::BC3t => &PixelFormatInfo {
                bytes_per_block: 16,
                channels: 4,
                has_alpha: true,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC3Unorm,
                name: "BC3",
                is_compressed: true,
            },
            EPixelFormat::BC4 => &PixelFormatInfo {
                bytes_per_block: 8,
                channels: 1,
                has_alpha: false,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC4Unorm,
                name: "BC4",
                is_compressed: true,
            },
            EPixelFormat::BC4s => &PixelFormatInfo {
                bytes_per_block: 8,
                channels: 1,
                has_alpha: false,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC4Snorm,
                name: "BC4s",
                is_compressed: true,
            },
            EPixelFormat::BC5 => &PixelFormatInfo {
                bytes_per_block: 16,
                channels: 2,
                has_alpha: false,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC5Unorm,
                name: "BC5",
                is_compressed: true,
            },
            EPixelFormat::BC5s => &PixelFormatInfo {
                bytes_per_block: 16,
                channels: 2,
                has_alpha: false,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC5Snorm,
                name: "BC5s",
                is_compressed: true,
            },
            EPixelFormat::BC6UH => &PixelFormatInfo {
                bytes_per_block: 16,
                channels: 3,
                has_alpha: false,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC6HUf16,
                name: "BC6UH",
                is_compressed: true,
            },
            EPixelFormat::BC7 | EPixelFormat::BC7t => &PixelFormatInfo {
                bytes_per_block: 16,
                channels: 4,
                has_alpha: true,
                min_width: 4,
                min_height: 4,
                block_width: 4,
                block_height: 4,
                dxgi_format: DxgiFormat::BC7Unorm,
                name: "BC7",
                is_compressed: true,
            },
            _ => &PixelFormatInfo {
                bytes_per_block: 4,
                channels: 4,
                has_alpha: true,
                min_width: 1,
                min_height: 1,
                block_width: 1,
                block_height: 1,
                dxgi_format: DxgiFormat::B8G8R8A8Unorm,
                name: "Fallback",
                is_compressed: false,
            },
        }
    }

    pub fn find_pixel_format_by_name(name: &str) -> Option<EPixelFormat> {
        match name.trim().to_ascii_uppercase().as_str() {
            "A8R8G8B8" | "ARGB8" | "RGBA8" => Some(EPixelFormat::A8R8G8B8),
            "X8R8G8B8" | "RGB8" | "RGBX8" => Some(EPixelFormat::X8R8G8B8),
            "R8G8B8" => Some(EPixelFormat::R8G8B8),
            "DXT1" | "BC1" => Some(EPixelFormat::BC1),
            "DXT1A" | "BC1A" => Some(EPixelFormat::BC1a),
            "DXT3" | "BC2" => Some(EPixelFormat::BC2),
            "DXT5" | "BC3" => Some(EPixelFormat::BC3),
            "3DC" | "BC5" => Some(EPixelFormat::BC5),
            "3DCP" | "BC4" => Some(EPixelFormat::BC4),
            "BC4S" => Some(EPixelFormat::BC4s),
            "BC5S" => Some(EPixelFormat::BC5s),
            "BC6UH" | "BC6H" => Some(EPixelFormat::BC6UH),
            "BC7" => Some(EPixelFormat::BC7),
            "BC7T" => Some(EPixelFormat::BC7t),
            "CTX1" => Some(EPixelFormat::CTX1),
            _ => None,
        }
    }

    /// Emulates CryEngine logic for automatically upgrading or downgrading the format quality
    /// based on the actual presence of an alpha channel.
    pub fn get_final_pixel_format(requested: EPixelFormat, has_alpha: bool) -> EPixelFormat {
        match (requested, has_alpha) {
            // Format upgrade (alpha is present, but the preset specifies a format without alpha)
            (EPixelFormat::X8R8G8B8, true) => EPixelFormat::A8R8G8B8,
            (EPixelFormat::R8G8B8, true) => EPixelFormat::A8R8G8B8,
            (EPixelFormat::BC1, true) => EPixelFormat::BC3, // DXT1 -> DXT5

            // Format downgrading to save memory and time (there is effectively no alpha channel)
            (EPixelFormat::A8R8G8B8, false) => EPixelFormat::X8R8G8B8,
            (EPixelFormat::BC1a, false) => EPixelFormat::BC1,
            (EPixelFormat::BC2, false) | (EPixelFormat::BC2t, false) => EPixelFormat::BC1,
            (EPixelFormat::BC3, false) | (EPixelFormat::BC3t, false) => EPixelFormat::BC1,
            (EPixelFormat::BC7t, false) => EPixelFormat::BC7, // Снимаем режим "t" (веса по альфе), оставляем BC7

            // Otherwise, leave as requested
            (fmt, _) => fmt,
        }
    }
}
